### PR TITLE
Fix fade lag

### PR DESCRIPTION
**Pull request by ErikReider**
Sets the cairo filter to bilinear

### CODE REVIEW

**Comment by jirutka** [comment]
Can you please explain what exactly this fixes and how?

**Comment by ErikReider** [comment]
> Can you please explain what exactly this fixes and how?

When rendering a large background with fade, the fade stutters. This makes it a bit more smooth

**Comment by jirutka** [comment]
The default filter (`CAIRO_FILTER_DEFAULT`) is `CAIRO_FILTER_GOOD`, which is described as “A reasonable-performance filter, with quality similar to `CAIRO_FILTER_BILINEAR`”. According to this, I would guess that the default filter is more performant than `CAIRO_FILTER_BILINEAR`, so I don’t understand how this change can fix lagging…?

**Comment by ErikReider** [comment]
> The default filter (`CAIRO_FILTER_DEFAULT`) is `CAIRO_FILTER_GOOD`, which is described as “A reasonable-performance filter, with quality similar to `CAIRO_FILTER_BILINEAR`”. According to this, I would guess that the default filter is more performant than `CAIRO_FILTER_BILINEAR`, so I don’t understand how this change can fix lagging…?

Oh yeah! Very strange... I've now tested setting it to `CAIRO_FILTER_BILINEAR` and `CAIRO_FILTER_GOOD` and the former does indeed lag less somehow on my hardware... Would you like a video example?

**Comment by jirutka** [comment]
> Would you like a video example?

Yeah, that would be useful!

**Comment by ErikReider** [comment]
> Yeah, that would be useful!

https://github.com/jirutka/swaylock-effects/assets/35975961/a406716b-5ca8-4d96-afff-be3a11ba4574

**Comment by ErikReider** [comment]
Here's a working video....

https://github.com/jirutka/swaylock-effects/assets/35975961/cf193a1a-3f40-4d1c-9c64-d561a5d643df

**Comment by jirutka** [comment]
Weird, I see _“Maintainers are allowed to edit this pull request.” _ in this PR, but I cannot push to your repository to rebase it:

```
$ git push -f git@github.com:ErikReider/swaylock-effects.git pr/37:lag-fix
ERROR: Permission to ErikReider/swaylock-effects.git denied to jirutka.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jirutka** [comment]
Merged as 7c5681ce96587ce3090c6698501faeccdfdc157d.

**Pull request closed without merging**
