### PR TITLE
Fixes for Sway 1.8+

### LINKED ISSUE #3: Stuck on red screen.
After this package was brought inline with upstream, it no longer works for me. The screen turns completely red except for the cursor, which is still visible and usable. Typing does not bring up the indicator or allow me to unlock, I have to reboot using the power button to get back in. It doesn't seem to be related to any config option, as simply running swaylock from a terminal causes the issue. This is happening on both my personl and work systems, both running Arch Linux, one with intel+nvida graphics and one with AMD, so it doesn't seem to be related to graphics drivers. I have tried with both sway (and wlroots) stable and sway-git (wlroots-git), issue occurs in both scenarios.

Output of `swaylock -d 2> log.txt`:
```
2022-07-17 12:57:27 - [main.c:1834] Parsing CLI Args
2022-07-17 12:57:27 - [main.c:1881] Using ext-session-lock-v1
2022-07-17 12:57:27 - [main.c:688] output name is HDMI-A-1
2022-07-17 12:57:27 - [main.c:344] Surface for output HDMI-A-1 ready
2022-07-17 12:57:27 - [main.c:688] output name is eDP-1
2022-07-17 12:57:27 - [main.c:344] Surface for output eDP-1 ready
ext_session_lock_surface_v1@21: error 0: session lock surface has never been configured
```

### PR DESCRIPTION
**Pull request by PeterCxy**
Fixes #3 and #5. See commit log for details.

### CODE REVIEW

**Comment by PeterCxy** [comment]
Note that the fade in effect is not working as intended on Sway 1.8+ still. The old approach relied on the alpha channel, which no longer works when the screen is locked by ext_session_lock_v1. We need to actually implement alpha blending, but I'll leave that for a future PR.

**Comment by PeterCxy** [comment]
fade-in should now work as well, save for the brief moment of flickering you will see due to delays between locking the screen and processing the effects. I'm not sure how one would go about fixing that flickering, though.

**Comment by PeterCxy** [comment]
Also due to the alpha blending, the performance of fade-in is now much worse than before (because that only required setting an alpha channel). However, it is not really noticeable for me when used with the screenshot option, so I think this should be fine at least before someone comes up with a better solution :)

**Comment by PeterCxy** [comment]
The flickering is now further reduced by applying effects before requesting for screen lock. I think it is now working reasonably well -- refactoring to use OpenGL rendering would be way too much work and at that point one might as well just start over and write another new implementation entirely.

**Comment by ccakes** [comment]
Confirming this fixes swaylock with `--screenshots` for me - on an NVIDIA GPU with Vulkan renderer

**Comment by Pato05** [comment]
Can confirm this works, even though there's flickering when swaylock is started and a very noticeable delay before the screenshot is blurred.

**Comment by luispabon** [comment]
> Can confirm this works, even though there's flickering when swaylock is started and a very noticeable delay before the screenshot is blurred.

I'm seeing this as well

**Comment by PeterCxy** [comment]
The flickering cannot be solved unless the ext_session_lock_v1 protocol is revised (to allow clients to set up the lock buffer *before* applying the lock). Not exactly sure what is the cause of the delay, though, since at that point all the heavy lifting should have been done already. I might look into this a bit later.

**Comment by PeterCxy** [comment]
@bd-g Could you share the parameters you are running swaylock with?

**Comment by bd-g** [comment]
```
swaylock -f --text-color FFFFFF \
    --screenshots \
    --clock \
    --indicator \
    --indicator-caps-lock \
    --indicator-radius 100 \
    --indicator-thickness 7 \
    --effect-blur 7x5 \
    \
    --ring-color 000099 \
    --line-color FFFFFF \
    --inside-color 667799 \
    --text-color FFFFFF \
    --key-hl-color 3399FF \
    --bs-hl-color 004080 \
    \
    --ring-ver-color 667799 \
    --line-ver-color 363663 \
    --inside-ver-color 667799 \
    --text-ver-color FFFFFF \
    \
    --ring-wrong-color B30000\
    --line-wrong-color FFFFFF \
    --inside-wrong-color 6B4747 \
    --text-wrong-color FFFFFF \
    \
    --separator-color FFFFFF \
    \
    --ring-caps-lock-color 804D4D \
    --line-caps-lock-color FFFFFF \
    --inside-caps-lock-color 804D4D \
    --text-caps-lock-color 4D0000 \
    --caps-lock-key-hl-color 4D0000 \
    --caps-lock-bs-hl-color FFFFFF \
    \
    --grace 5 \
    --fade-in 1
```

**Comment by luispabon** [comment]
With those parameters swaylock crashes as soon as I start typing with this error:

```
2023-01-10 16:51:58 - [main.c:626] Screencopy failed
```

**Comment by bd-g** [comment]
> swaylock -f --text-color FFFFFF \
>     --screenshots \
>     --clock \
>     --indicator \
>     --indicator-caps-lock \
>     --indicator-radius 100 \
>     --indicator-thickness 7 \
>     --effect-blur 7x5 \
>     \
>     --ring-color 000099 \
>     --line-color FFFFFF \
>     --inside-color 667799 \
>     --text-color FFFFFF \
>     --key-hl-color 3399FF \
>     --bs-hl-color 004080 \
>     \
>     --ring-ver-color 667799 \
>     --line-ver-color 363663 \
>     --inside-ver-color 667799 \
>     --text-ver-color FFFFFF \
>     \
>     --ring-wrong-color B30000\
>     --line-wrong-color FFFFFF \
>     --inside-wrong-color 6B4747 \
>     --text-wrong-color FFFFFF \
>     \
>     --separator-color FFFFFF \
>     \
>     --ring-caps-lock-color 804D4D \
>     --line-caps-lock-color FFFFFF \
>     --inside-caps-lock-color 804D4D \
>     --text-caps-lock-color 4D0000 \
>     --caps-lock-key-hl-color 4D0000 \
>     --caps-lock-bs-hl-color FFFFFF \
>     \
>     --grace 5 \
>     --fade-in 1

This command works for me on both the jirutka:master build and the PeterCxy:sway-1.8-fixes build when running sway v1.7-10. When I run with sway v1.8-3, the screen flahses white and locks, as described.

**Comment by PeterCxy** [comment]
@bd-g Can you try the command without `-f` (daemonization)? That could be the problem here. If that fixes it for you, then I'll take a look into why daemonization is broken.

**Comment by bd-g** [comment]
> @bd-g Can you try the command without `-f` (daemonization)? That could be the problem here. If that fixes it for you, then I'll take a look into why daemonization is broken.

Problem still persists for me even without the -f flag. Let me know if you want more logs or system details.

**Comment by PeterCxy** [comment]
@bd-g Can you run the command with `-d` for debug output and post it here? Your exact command works perfectly on my environment.

**Comment by bd-g** [comment]
```
2023-01-10 14:19:04 - [main.c:1842] Parsing CLI Args
2023-01-10 14:19:04 - [main.c:1889] Using ext-session-lock-v1
2023-01-10 14:19:04 - [main.c:688] output name is eDP-1
2023-01-10 14:19:04 - [main.c:650] Loaded screenshot for output eDP-1
2023-01-10 14:19:04 - [main.c:344] Surface for output eDP-1 ready
```

**Comment by PeterCxy** [comment]
@bd-g Ok, that is very weird, because in your debug log the line numbers do *not* match up with my source files at all. The `Using ext-session-lock-v1` log message should be from line 1911 https://github.com/PeterCxy/swaylock-effects/blob/sway-1.8-fixes/main.c#L1911, and it should happen *after* the `Loaded screenshot for output` message (whose line number is also not correct at all). Are you sure the correct binary is executed?

**Comment by bd-g** [comment]
> @bd-g Ok, that is very weird, because in your debug log the line numbers do _not_ match up with my source files at all. The `Using ext-session-lock-v1` log message should be from line 1911 https://github.com/PeterCxy/swaylock-effects/blob/sway-1.8-fixes/main.c#L1911, and it should happen _after_ the `Loaded screenshot for output` message (whose line number is also not correct at all). Are you sure the correct binary is executed?

Ah, I found my mistake. I was using the master branch from your fork, not the sway-1.8-fixes. Cloned and forgot to switch branches. I can now confirm that the screenshot functionality *does* work for me, although I do have the blinking problem mentioned by others. As of now, no red screen of death, but I'll reply if I do see one.

**Comment by PeterCxy** [comment]
Note that there is now a new upstream release that works on sway 1.8 too, but that is using an older deprecated way of locking the session (`wlr_layer_shell` + `wlr_input_inhibitor`), which is less secure and may be removed in the future from compositors. This PR is still the only way something like swaylock-effects can work with the better `ext_session_lock_v1` protocol.

**Comment by PeterCxy** [comment]
Fixed formatting.

**Comment by bd-g** [comment]
@PeterCxy just a question on implementation - I noticed that there is no longer a flicker showing the full screen when the system is resumed (like closing and reopening the lid of a laptop) - that's awesome! On the other hand, it appears the screenshot effect is reset. Does this fall under the category of "too difficult to fix with the current architecture"?

For example, if I manually run swaylock, it locks my screen with a screenshot image and a given blur setting. Then, I can close the lid of my laptop, triggering a suspend. If I then open the lid and resume my session, the lock screen is the only thing that shows (there is no longer a 1-2 second flicker of the underlying screen). However, it is now just a blank white screen, as opposed to being a screenshot. I assume it is retaking the screenshot while the lid is closed, leading to a blank white background?

**Comment by PeterCxy** [comment]
@bd-g I have no idea, there should not be any new screenshot being taken while resuming, unless your Wayland compositor is re-launching swaylock-effects itself. If that is the case, then there isn't really much we can do about it.

**Comment by PeterCxy** [comment]
@bd-g Or maybe the output events are sent again after resume? In that case we can try calling `zxdg_output_manager_v1_destroy` to destroy the output manager after screenshots have been taken.

**Comment by MarijnS95** [comment]
Seeing a similar issue as @bd-g when manually turning the monitors off on lock using DPMS:

```
set $lock_cmd swaylock -efF --fade-in 1 --indicator-idle-visible --clock -S --effect-pixelate 32
exec --no-startup-id swayidle -dw \
     timeout 305 'swaymsg "output * dpms off"' \
     timeout 300 '$lock_cmd --grace 5' \
          resume 'swaymsg "output * dpms on"' \
    before-sleep '$lock_cmd'
```

This results in a black screen when the panels turn back on.

**Comment by MarijnS95** [comment]
@PeterCxy I had programmed it to not go to sleep.

Regardless, since I do also use sleep _manually_ at times, is there a way to teach `swayidle` to not relaunch the lock session if one is already running? Seems incorrect to me.

**Comment by PeterCxy** [comment]
@MarijnS95 Can you enable the debug flag, run swaylock in some terminal or pipe the log output somewhere, and then do the same sequence of actions that triggers the bug? That would help diagnosing what is happening.

**Comment by PeterCxy** [comment]
In any case, I probably know what is happening. When the output array changes, a Wayland global registry event will be triggered, and the handler [here](https://github.com/jirutka/swaylock-effects/blob/cd07dd1082a2fc1093f1e6f2541811e446f4d114/main.c#L766) will call create_surface to add a new lockscreen surface. But because we are already in the locked state here, we cannot obtain screenshots of the new display, and it ends up just being completely white. Now the question is what would be a sensible default in this case other than displaying the white image.

**Comment by bd-g** [comment]
> In any case, I probably know what is happening. When the output array changes, a Wayland global registry event will be triggered, and the handler [here](https://github.com/jirutka/swaylock-effects/blob/cd07dd1082a2fc1093f1e6f2541811e446f4d114/main.c#L766) will call create_surface to add a new lockscreen surface. But because we are already in the locked state here, we cannot obtain screenshots of the new display, and it ends up just being completely white. Now the question is what would be a sensible default in this case other than displaying the white image.

If the display is already displayed and we cannot cache the screenshot in any way, perhaps allow for both the image and the screenshot option to be passed? And then if we detect a fully white screenshot, default to the image?

**Comment by MarijnS95** [comment]
@PeterCxy It seems to be working now, the screenshot survives both a `dpms off` -> `dpms on` pair as well as suspend. Not sure if that's caused by the newer commits or this being a different machine (laptop vs desktop), both have a single monitor.

By the way `-d` logging uses black text which is invisible on a black background :upside_down_face: 

```console
$ swaylock -eF -S --effect-pixelate 20 --fade 2 -d
2023-01-11 17:26:08 - [main.c:1824] Parsing CLI Args
2023-01-11 17:26:08 - [main.c:680] output name is eDP-1
2023-01-11 17:26:08 - [main.c:641] Loaded screenshot for output eDP-1
2023-01-11 17:26:08 - [main.c:1911] Using ext-session-lock-v1
```

**Comment by MarijnS95** [comment]
@PeterCxy fwiw it seems upstream `swaylock` is pestered by the same problem. By default it jumps to a white background instantaneously, but when providing a background image with `-i` it  also takes a while, meanwhile showing a black/blanked screen. I'm curious what that white background does different, maybe the image is loaded "asynchronously"?

**Comment by bd-g** [comment]
> @PeterCxy It seems to be persisting the screenshot now, surviving both a `dpms off` -> `dpms on` pair as well as suspend. Not sure if that's caused by the newer commits (testing on [cd07dd1](https://github.com/jirutka/swaylock-effects/commit/cd07dd1082a2fc1093f1e6f2541811e446f4d114)) or this being a different machine (laptop vs desktop), both have a single monitor.
> 
> By the way `-d` logging uses black text which is invisible on a black background upside_down_face
> 
> ```
> $ swaylock -eF -S --effect-pixelate 20 --fade 2 -d
> 2023-01-11 17:26:08 - [main.c:1824] Parsing CLI Args
> 2023-01-11 17:26:08 - [main.c:680] output name is eDP-1
> 2023-01-11 17:26:08 - [main.c:641] Loaded screenshot for output eDP-1
> 2023-01-11 17:26:08 - [main.c:1911] Using ext-session-lock-v1
> ```
> 
> EDIT: Triple monitor system also persists the screenshot (with aforementioned command). So it's just the stutter that I hope can be resolved at some point :)

It's still not working for me on my laptop - did this work on your desktop? Perhaps because on a desktop, it's not "destroying" the surface completely - this is my output when running the same command on the most up to date commit

```
$ ./swaylock -eF -S --effect-pixelate 20 --fade 2 -d
2023-01-11 14:08:00 - [main.c:1824] Parsing CLI Args
2023-01-11 14:08:00 - [main.c:680] output name is eDP-1
2023-01-11 14:08:00 - [main.c:641] Loaded screenshot for output eDP-1
2023-01-11 14:08:00 - [main.c:1911] Using ext-session-lock-v1
2023-01-11 14:08:05 - [main.c:244] Destroy surface for output eDP-1
```

**Comment by jirutka** [comment]
Thanks for the excellent work, @PeterCxy, and to other participants for testing it!

Since many people confirmed that it works, I’m gonna merge it. @bd-g, feel free to open a new issue for that persisting problem.

**Comment by bd-g** [comment]
> Thanks for the excellent work, @PeterCxy, and to other participants for testing it!
> 
> Since many people confirmed that it works, I’m gonna merge it. @bd-g, feel free to open a new issue for that persisting problem.

I agree merging is the right way to do it - it is more secure (using `ext-session-lock-v1`), and I think that takes precendence over the screenshot issue.

**Pull request merged**
